### ISSUE TITLE
Width of Content Area

### ISSUE THREAD

**Issue by ck47-openstax** [openstax/labs#27]
The content area should be 1170px. I used openstax.org as reference if that helps. This will also make the images end up being around 570x363

<img width="1712" alt="Screen Shot 2021-07-13 at 8 28 25 AM" src="https://user-images.githubusercontent.com/74740978/125460502-9ffe0831-deac-48d7-9af7-022ba0579579.png">

**Comment by nathanstitt** [comment]
@ck47-openstax this is complete, please take a look at https://cms-dev.openstax.org/general/labs and see how it looks
