### ISSUE TITLE
Mobile Styles

### ISSUE THREAD

**Issue by ck47-openstax** [openstax/labs#28]
For mobile I would like to stack the content. The only sections that need attention are the ones that are in the attached screenshot. If you need to inspect it you can go the "Student Flow LoFi" figma file (the same file where the desktop landing page is). 
![Landing page - Mobile](https://user-images.githubusercontent.com/74740978/125466533-e6efd31b-3c71-4300-959f-c5f128171b1f.png)

**Comment by nathanstitt** [comment]
@ck47-openstax this is complete, please take a look at https://cms-dev.openstax.org/general/labs and see how it looks
